# Generated by Django 3.0.6 on 2020-05-31 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_load', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='predict_Map_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('map_coordinates_link', models.CharField(max_length=400)),
            ],
        ),
    ]
